### ISSUE TITLE
Crash when trying to choose a game mode on Android 4.4

### ISSUE THREAD

**Issue by Bastindo** [lexica/lexica#330]
# Behavior
Apps crashes with "Unfortunately, Lexica has stopped" when opening the game mode menu.

# How to reproduce
1. Install Lexica on an Android 4.4.x device
2. Open the app
3. Tap the game mode button

# Log
```
E/AndroidRuntime( 2469): FATAL EXCEPTION: main
E/AndroidRuntime( 2469): Process: com.serwylo.lexica, PID: 2469
E/AndroidRuntime( 2469): android.view.InflateException: Binary XML file line #36: Error inflating class com.serwylo.lexica.view.GameDetailsView
E/AndroidRuntime( 2469): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
E/AndroidRuntime( 2469): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
E/AndroidRuntime( 2469): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
E/AndroidRuntime( 2469): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime( 2469): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
E/AndroidRuntime( 2469): 	at com.serwylo.lexica.databinding.GameModeItemBinding.inflate(GameModeItemBinding.java:53)
E/AndroidRuntime( 2469): 	at com.serwylo.lexica.ChooseGameModeActivity$Adapter.onCreateViewHolder(ChooseGameModeActivity.kt:73)
E/AndroidRuntime( 2469): 	at com.serwylo.lexica.ChooseGameModeActivity$Adapter.onCreateViewHolder(ChooseGameModeActivity.kt:67)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
E/AndroidRuntime( 2469): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1855)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1717)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1571)
E/AndroidRuntime( 2469): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1480)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime( 2469): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime( 2469): 	at android.view.View.layout(View.java:14841)
E/AndroidRuntime( 2469): 	at android.view.ViewGroup.layout(ViewGroup.java:4631)
E/AndroidRuntime( 2469): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
E/AndroidRuntime( 2469): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1743)
E/AndroidRuntime( 2469): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
E/AndroidRuntime( 2469): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
E/AndroidRuntime( 2469): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
E/AndroidRuntime( 2469): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
E/AndroidRuntime( 2469): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
E/AndroidRuntime( 2469): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
E/AndroidRuntime( 2469): 	at android.os.Handler.h
W/ActivityManager(  549):   Force finishing activity com.serwylo.lexica/.ChooseGameModeActivity
W/ActivityManager(  549):   Force finishing activity com.serwylo.lexica/.MainMenuActivity
```

Lexica version: 3.6.1
Android version: tried on Stock Samsung Android 4.4.2 and CyanogenMod Android 4.4.4
Device: tried on Samsung Galaxy Tab 4 7.0, Samsung Galaxy Ace, Amazon Fire Phone

**Comment by pserwylo** [comment]
Oh, this is not good. Thanks for the report, including the logcat output especially. I'll try to find some time to reproduce and see if it is simple enough to fix, but it may be another week or two before finding the time to do so.
