### ISSUE TITLE
Crash when using spanish dictionary

### ISSUE THREAD

**Issue by kaeza** [lexica/lexica#76]
App crashes as soon as you click on new game button.

```
java.lang.ArrayIndexOutOfBoundsException: length=26; index=136
	at com.serwylo.lexica.game.Game.letterPoints(Game.java:400)
	at com.serwylo.lexica.view.LexicaView.drawBoard(LexicaView.java:168)
	at com.serwylo.lexica.view.LexicaView.onDraw(LexicaView.java:376)
	at android.view.View.draw(View.java:16201)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.updateDisplayListIfDirty(View.java:15193)
	at android.view.View.draw(View.java:15971)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3610)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3400)
	at android.view.View.draw(View.java:16204)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
	at android.view.View.updateDisplayListIfDirty(View.java:15198)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:282)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:288)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:323)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2642)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2461)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
	at android.view.Choreographer.doFrame(Choreographer.java:608)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

Edit: Lexica 0.11.2 from F-Droid.

**Comment by pserwylo** [comment]
Thanks for the report @kaeza. This is because I forgot to make the "Letter points" scoring feature work with different languages beyond just English. It presumes all languages have only the 26 characters from the English alphabet (because the feature was added just before the work on international dictionaries). 

Would it be suitable if I used the same scoring as I do for English, except `á`, `é`, `í`, `ó`, `ú`, `ü`, and `ñ` are worth the same as `a`, `e`, `i`, `o`, `u`, `u`, `n`?

**Comment by pserwylo** [comment]
Actually, how about we use scores like those from here: https://en.wikipedia.org/wiki/Scrabble_letter_distributions#Spanish. Except I'll not bother with the scores for tiles like "ch" and "rr", just single letter tiles. Does that sound alright?

**Comment by kaeza** [comment]
@pserwylo Thanks for taking the time to investigate this. Either option is fine.
